version: '3.8'

services:
  nginx:
    image: ticketinghub-nginx:latest
    ports:
      - "80:80"
    networks:
      - ticketing-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  backend:
    image: ticketinghub-backend:latest
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/ticketing_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
    networks:
      - ticketing-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  worker:
    image: ticketinghub-worker:latest
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - ticketing-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticketing_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ticketing-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  redis:
    image: redis:alpine
    networks:
      - ticketing-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  ticketing-net:
    driver: overlay

volumes:
  postgres-data:
